#!/bin/bash

function loadSourceScripts {
	currentDirPath=$(dirname $0)

	## rm previous tmp script
	if [ -f $currentDirPath/source/main-script/tmp/varFile ] ; then
		rm $currentDirPath/source/main-script/tmp/varFile
	fi

	## Populate Bash session with source script
	for i in $currentDirPath/source/main-script/*.sh; do
		source "$i" -H ## || break
	done

}

function useTheLoadedSource {
	sleep 1s
	mainInit
	myMian
}

function installSoftwareMultimedia {
	clear
	echo "Checking internet connection ..."
	sleep 3s
	myPingAddr=google.com
	ping -c1 $myPingAddr &>/dev/null
	pingFlag=$?
	sleep 1s

	if [ $pingFlag -eq 0 ]; then
		echo -e "Checking the internet for updates and app prerequisites.\n\n\tStand by ... This may take a moment ..."
		echo -e "\n\tYou will be prompted to install GNU software if needed.\n\tYou will also get the latest app updates from [ https://github.com/mezcel/jq-tput-terminal.git ].\n"

		currentDirPath=$(dirname $0)

		## gnu software
		bash "$currentDirPath/source/gnu/download-gnu-software"

		## audio
		bash "$currentDirPath/source/ogg/download-ogg-media"
	fi
}

## RUN APP

installSoftwareMultimedia

loadSourceScripts

useTheLoadedSource
