#!/bin/bash

function loadSourceScripts {
	currentDirPath=$(dirname $0)
	
	for i in $currentDirPath/source/*.txt; do
		source "$i" -H   || break
	done
	
}

function useTheLoadedSource {	
	mainInit
	myMian
}

## RUN APP

loadSourceScripts

useTheLoadedSource
