#!/bin/bash

function download_ogg_media {
	## Populate Dir with Audio for use within this app

	currentDirPath=$(dirname $0)

	## install from list, and install only if file does not exist
	wget -q -nc -i $currentDirPath/ogg-list.txt -P $currentDirPath/
}

download_ogg_media
