#!/bin/bash

function my_titlebar {
	myTitle=$1
	#echo -e '\033k'$myTitle'\033\\'
	echo -e '\033]2;'$myTitle'\007'
}

function download_ogg_media {
	## Populate Dir with Audio for use within this app
	currentDirPath=$(dirname $0)

	sudo ping -c3 google.com &>/dev/null
	pingTest=$?
	if [ $pingTest -eq 0 ]; then
		## install from list, and install only if file does not exist
		echo "Downloading any missing audio ..."
		#wget -q -nc -i $currentDirPath/ogg-list.txt -P $currentDirPath/
		wget -nv -nc -i $currentDirPath/ogg-list.txt -P $currentDirPath/

		echo "Done checking for audio."
	fi
}

## RUN

my_titlebar "bash-rosary (install libre audio)"
download_ogg_media
