#!/bin/bash

## I assume most linux distros will have awk, sed, and wget

function download_audio {
	currentDirPath=$(dirname $0)

	bash "$currentDirPath/audio/dl-app-audio"
}


function linuxDistroArch {
	## Pacman
	sudo pacman -S --needed bash xterm grep sed wget gawk bc curl ncurses dialog jq gcc vorbis-tools elinks git

	## Fix for ogg123 (vorbis-tools)
	sed -i -e 's/dev=default/# dev=default/g' /etc/libao.conf

}

function linuxDistroDebian {
	## Debian Apt

	sudo apt-get install bash xterm grep sed wget gawk bc curl grep sed wget gawk bc curl libncurses5-dev libncursesw5-dev dialog jq gcc vorbis-tools elinks

}
